//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESTM.Web.BLL.ServiceReference_PowerManager {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MemberBindingType", Namespace="http://schemas.datacontract.org/2004/07/System.Linq.Expressions")]
    public enum MemberBindingType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Assignment = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberBinding = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ListBinding = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MemberNodeGeneric", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Serialize.Linq.Nodes.MethodInfoNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Serialize.Linq.Nodes.PropertyInfoNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Serialize.Linq.Nodes.ConstructorInfoNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Serialize.Linq.Nodes.FieldInfoNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Serialize.Linq.Nodes.MemberInfoNode))]
    public partial class MemberNodeGeneric : Serialize.Linq.Nodes.Node, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Serialize.Linq.Nodes.TypeNode DeclaringTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignatureField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Serialize.Linq.Nodes.TypeNode DeclaringType {
            get {
                return this.DeclaringTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DeclaringTypeField, value) != true)) {
                    this.DeclaringTypeField = value;
                    this.RaisePropertyChanged("DeclaringType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Signature {
            get {
                return this.SignatureField;
            }
            set {
                if ((object.ReferenceEquals(this.SignatureField, value) != true)) {
                    this.SignatureField = value;
                    this.RaisePropertyChanged("Signature");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="MemberBindingNodeList", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes", ItemName="MemberBindingNode")]
    [System.SerializableAttribute()]
    public class MemberBindingNodeList : System.Collections.Generic.List<Serialize.Linq.Nodes.MemberBindingNode> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ElementInitNodeList", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes", ItemName="ElementInitNode")]
    [System.SerializableAttribute()]
    public class ElementInitNodeList : System.Collections.Generic.List<Serialize.Linq.Nodes.ElementInitNode> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ExpressionNodeList", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes", ItemName="ExpressionNode")]
    [System.SerializableAttribute()]
    public class ExpressionNodeList : System.Collections.Generic.List<Serialize.Linq.Nodes.ExpressionNode> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExpressionType", Namespace="http://schemas.datacontract.org/2004/07/System.Linq.Expressions")]
    public enum ExpressionType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Add = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AddChecked = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        And = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AndAlso = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ArrayLength = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ArrayIndex = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Call = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Coalesce = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Conditional = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Constant = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Convert = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConvertChecked = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Divide = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Equal = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExclusiveOr = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GreaterThan = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GreaterThanOrEqual = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invoke = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Lambda = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LeftShift = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LessThan = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LessThanOrEqual = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ListInit = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberAccess = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberInit = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Modulo = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Multiply = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MultiplyChecked = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Negate = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnaryPlus = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NegateChecked = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        New = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NewArrayInit = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NewArrayBounds = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Not = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotEqual = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Or = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrElse = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Parameter = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Power = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Quote = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RightShift = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Subtract = 42,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SubtractChecked = 43,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TypeAs = 44,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TypeIs = 45,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Assign = 46,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Block = 47,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DebugInfo = 48,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Decrement = 49,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Dynamic = 50,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Default = 51,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Extension = 52,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Goto = 53,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Increment = 54,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Index = 55,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Label = 56,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RuntimeVariables = 57,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Loop = 58,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Switch = 59,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Throw = 60,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Try = 61,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unbox = 62,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AddAssign = 63,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AndAssign = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DivideAssign = 65,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExclusiveOrAssign = 66,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LeftShiftAssign = 67,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ModuloAssign = 68,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MultiplyAssign = 69,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrAssign = 70,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PowerAssign = 71,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RightShiftAssign = 72,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SubtractAssign = 73,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AddAssignChecked = 74,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MultiplyAssignChecked = 75,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SubtractAssignChecked = 76,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PreIncrementAssign = 77,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PreDecrementAssign = 78,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PostIncrementAssign = 79,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PostDecrementAssign = 80,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TypeEqual = 81,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OnesComplement = 82,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IsTrue = 83,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IsFalse = 84,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExpressionNodeGeneric", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Serialize.Linq.Nodes.MemberInitExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Serialize.Linq.Nodes.NewExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Serialize.Linq.Nodes.ConditionalExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Serialize.Linq.Nodes.MethodCallExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Serialize.Linq.Nodes.NewArrayExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Serialize.Linq.Nodes.MemberExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Serialize.Linq.Nodes.ParameterExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Serialize.Linq.Nodes.TypeBinaryExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Serialize.Linq.Nodes.UnaryExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Serialize.Linq.Nodes.BinaryExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Serialize.Linq.Nodes.ConstantExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Serialize.Linq.Nodes.InvocationExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Serialize.Linq.Nodes.LambdaExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Serialize.Linq.Nodes.ListInitExpressionNode))]
    public partial class ExpressionNodeGeneric : Serialize.Linq.Nodes.ExpressionNode, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="MemberInfoNodeList", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes", ItemName="MemberInfoNode")]
    [System.SerializableAttribute()]
    public class MemberInfoNodeList : System.Collections.Generic.List<Serialize.Linq.Nodes.MemberInfoNode> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_PowerManager.IPowerManageWCFService")]
    public interface IPowerManageWCFService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPowerManageWCFService/GetUsers", ReplyAction="http://tempuri.org/IPowerManageWCFService/GetUsersResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ESTM.Web.BLL.ServiceReference_PowerManager.ExpressionNodeGeneric))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.MemberInitExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.NewExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.ConditionalExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.MethodCallExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.NewArrayExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.MemberExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.ParameterExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.TypeBinaryExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.UnaryExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.BinaryExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.ConstantExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.InvocationExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.LambdaExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.ListInitExpressionNode))]
        System.Collections.Generic.List<ESTM.Common.DtoModel.DTO_TB_USERS> GetUsers(Serialize.Linq.Nodes.ExpressionNode expressionNode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPowerManageWCFService/GetUsers", ReplyAction="http://tempuri.org/IPowerManageWCFService/GetUsersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ESTM.Common.DtoModel.DTO_TB_USERS>> GetUsersAsync(Serialize.Linq.Nodes.ExpressionNode expressionNode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPowerManageWCFService/AddUser", ReplyAction="http://tempuri.org/IPowerManageWCFService/AddUserResponse")]
        ESTM.Common.DtoModel.DTO_TB_USERS AddUser(ESTM.Common.DtoModel.DTO_TB_USERS oUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPowerManageWCFService/AddUser", ReplyAction="http://tempuri.org/IPowerManageWCFService/AddUserResponse")]
        System.Threading.Tasks.Task<ESTM.Common.DtoModel.DTO_TB_USERS> AddUserAsync(ESTM.Common.DtoModel.DTO_TB_USERS oUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPowerManageWCFService/DeleteUser", ReplyAction="http://tempuri.org/IPowerManageWCFService/DeleteUserResponse")]
        bool DeleteUser(ESTM.Common.DtoModel.DTO_TB_USERS oUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPowerManageWCFService/DeleteUser", ReplyAction="http://tempuri.org/IPowerManageWCFService/DeleteUserResponse")]
        System.Threading.Tasks.Task<bool> DeleteUserAsync(ESTM.Common.DtoModel.DTO_TB_USERS oUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPowerManageWCFService/DeleteUserByLamada", ReplyAction="http://tempuri.org/IPowerManageWCFService/DeleteUserByLamadaResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ESTM.Web.BLL.ServiceReference_PowerManager.ExpressionNodeGeneric))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.MemberInitExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.NewExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.ConditionalExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.MethodCallExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.NewArrayExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.MemberExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.ParameterExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.TypeBinaryExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.UnaryExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.BinaryExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.ConstantExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.InvocationExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.LambdaExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.ListInitExpressionNode))]
        bool DeleteUserByLamada(Serialize.Linq.Nodes.ExpressionNode expressionNode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPowerManageWCFService/DeleteUserByLamada", ReplyAction="http://tempuri.org/IPowerManageWCFService/DeleteUserByLamadaResponse")]
        System.Threading.Tasks.Task<bool> DeleteUserByLamadaAsync(Serialize.Linq.Nodes.ExpressionNode expressionNode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPowerManageWCFService/UpdateUser", ReplyAction="http://tempuri.org/IPowerManageWCFService/UpdateUserResponse")]
        bool UpdateUser(ESTM.Common.DtoModel.DTO_TB_USERS oUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPowerManageWCFService/UpdateUser", ReplyAction="http://tempuri.org/IPowerManageWCFService/UpdateUserResponse")]
        System.Threading.Tasks.Task<bool> UpdateUserAsync(ESTM.Common.DtoModel.DTO_TB_USERS oUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPowerManageWCFService/GetDepartments", ReplyAction="http://tempuri.org/IPowerManageWCFService/GetDepartmentsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ESTM.Web.BLL.ServiceReference_PowerManager.ExpressionNodeGeneric))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.MemberInitExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.NewExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.ConditionalExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.MethodCallExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.NewArrayExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.MemberExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.ParameterExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.TypeBinaryExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.UnaryExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.BinaryExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.ConstantExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.InvocationExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.LambdaExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.ListInitExpressionNode))]
        System.Collections.Generic.List<ESTM.Common.DtoModel.DTO_TB_DEPARTMENT> GetDepartments(Serialize.Linq.Nodes.ExpressionNode expressionNode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPowerManageWCFService/GetDepartments", ReplyAction="http://tempuri.org/IPowerManageWCFService/GetDepartmentsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ESTM.Common.DtoModel.DTO_TB_DEPARTMENT>> GetDepartmentsAsync(Serialize.Linq.Nodes.ExpressionNode expressionNode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPowerManageWCFService/AddDepartment", ReplyAction="http://tempuri.org/IPowerManageWCFService/AddDepartmentResponse")]
        ESTM.Common.DtoModel.DTO_TB_DEPARTMENT AddDepartment(ESTM.Common.DtoModel.DTO_TB_DEPARTMENT oDept);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPowerManageWCFService/AddDepartment", ReplyAction="http://tempuri.org/IPowerManageWCFService/AddDepartmentResponse")]
        System.Threading.Tasks.Task<ESTM.Common.DtoModel.DTO_TB_DEPARTMENT> AddDepartmentAsync(ESTM.Common.DtoModel.DTO_TB_DEPARTMENT oDept);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPowerManageWCFService/DeleteDepartment", ReplyAction="http://tempuri.org/IPowerManageWCFService/DeleteDepartmentResponse")]
        bool DeleteDepartment(ESTM.Common.DtoModel.DTO_TB_DEPARTMENT oDept);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPowerManageWCFService/DeleteDepartment", ReplyAction="http://tempuri.org/IPowerManageWCFService/DeleteDepartmentResponse")]
        System.Threading.Tasks.Task<bool> DeleteDepartmentAsync(ESTM.Common.DtoModel.DTO_TB_DEPARTMENT oDept);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPowerManageWCFService/DeleteDeptByLamada", ReplyAction="http://tempuri.org/IPowerManageWCFService/DeleteDeptByLamadaResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ESTM.Web.BLL.ServiceReference_PowerManager.ExpressionNodeGeneric))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.MemberInitExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.NewExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.ConditionalExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.MethodCallExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.NewArrayExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.MemberExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.ParameterExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.TypeBinaryExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.UnaryExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.BinaryExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.ConstantExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.InvocationExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.LambdaExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.ListInitExpressionNode))]
        bool DeleteDeptByLamada(Serialize.Linq.Nodes.ExpressionNode expressionNode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPowerManageWCFService/DeleteDeptByLamada", ReplyAction="http://tempuri.org/IPowerManageWCFService/DeleteDeptByLamadaResponse")]
        System.Threading.Tasks.Task<bool> DeleteDeptByLamadaAsync(Serialize.Linq.Nodes.ExpressionNode expressionNode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPowerManageWCFService/UpdateDepartment", ReplyAction="http://tempuri.org/IPowerManageWCFService/UpdateDepartmentResponse")]
        bool UpdateDepartment(ESTM.Common.DtoModel.DTO_TB_DEPARTMENT oDept);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPowerManageWCFService/UpdateDepartment", ReplyAction="http://tempuri.org/IPowerManageWCFService/UpdateDepartmentResponse")]
        System.Threading.Tasks.Task<bool> UpdateDepartmentAsync(ESTM.Common.DtoModel.DTO_TB_DEPARTMENT oDept);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPowerManageWCFService/GetRoles", ReplyAction="http://tempuri.org/IPowerManageWCFService/GetRolesResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ESTM.Web.BLL.ServiceReference_PowerManager.ExpressionNodeGeneric))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.MemberInitExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.NewExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.ConditionalExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.MethodCallExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.NewArrayExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.MemberExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.ParameterExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.TypeBinaryExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.UnaryExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.BinaryExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.ConstantExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.InvocationExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.LambdaExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.ListInitExpressionNode))]
        System.Collections.Generic.List<ESTM.Common.DtoModel.DTO_TB_ROLE> GetRoles(Serialize.Linq.Nodes.ExpressionNode expressionNode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPowerManageWCFService/GetRoles", ReplyAction="http://tempuri.org/IPowerManageWCFService/GetRolesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ESTM.Common.DtoModel.DTO_TB_ROLE>> GetRolesAsync(Serialize.Linq.Nodes.ExpressionNode expressionNode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPowerManageWCFService/AddRole", ReplyAction="http://tempuri.org/IPowerManageWCFService/AddRoleResponse")]
        ESTM.Common.DtoModel.DTO_TB_ROLE AddRole(ESTM.Common.DtoModel.DTO_TB_ROLE oRole);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPowerManageWCFService/AddRole", ReplyAction="http://tempuri.org/IPowerManageWCFService/AddRoleResponse")]
        System.Threading.Tasks.Task<ESTM.Common.DtoModel.DTO_TB_ROLE> AddRoleAsync(ESTM.Common.DtoModel.DTO_TB_ROLE oRole);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPowerManageWCFService/GetMenus", ReplyAction="http://tempuri.org/IPowerManageWCFService/GetMenusResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ESTM.Web.BLL.ServiceReference_PowerManager.ExpressionNodeGeneric))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.MemberInitExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.NewExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.ConditionalExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.MethodCallExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.NewArrayExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.MemberExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.ParameterExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.TypeBinaryExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.UnaryExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.BinaryExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.ConstantExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.InvocationExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.LambdaExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Serialize.Linq.Nodes.ListInitExpressionNode))]
        System.Collections.Generic.List<ESTM.Common.DtoModel.DTO_TB_MENU> GetMenus(Serialize.Linq.Nodes.ExpressionNode expressionNode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPowerManageWCFService/GetMenus", ReplyAction="http://tempuri.org/IPowerManageWCFService/GetMenusResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ESTM.Common.DtoModel.DTO_TB_MENU>> GetMenusAsync(Serialize.Linq.Nodes.ExpressionNode expressionNode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPowerManageWCFService/AddMenu", ReplyAction="http://tempuri.org/IPowerManageWCFService/AddMenuResponse")]
        ESTM.Common.DtoModel.DTO_TB_MENU AddMenu(ESTM.Common.DtoModel.DTO_TB_MENU oMenu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPowerManageWCFService/AddMenu", ReplyAction="http://tempuri.org/IPowerManageWCFService/AddMenuResponse")]
        System.Threading.Tasks.Task<ESTM.Common.DtoModel.DTO_TB_MENU> AddMenuAsync(ESTM.Common.DtoModel.DTO_TB_MENU oMenu);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPowerManageWCFServiceChannel : ESTM.Web.BLL.ServiceReference_PowerManager.IPowerManageWCFService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PowerManageWCFServiceClient : System.ServiceModel.ClientBase<ESTM.Web.BLL.ServiceReference_PowerManager.IPowerManageWCFService>, ESTM.Web.BLL.ServiceReference_PowerManager.IPowerManageWCFService {
        
        public PowerManageWCFServiceClient() {
        }
        
        public PowerManageWCFServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PowerManageWCFServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PowerManageWCFServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PowerManageWCFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<ESTM.Common.DtoModel.DTO_TB_USERS> GetUsers(Serialize.Linq.Nodes.ExpressionNode expressionNode) {
            return base.Channel.GetUsers(expressionNode);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ESTM.Common.DtoModel.DTO_TB_USERS>> GetUsersAsync(Serialize.Linq.Nodes.ExpressionNode expressionNode) {
            return base.Channel.GetUsersAsync(expressionNode);
        }
        
        public ESTM.Common.DtoModel.DTO_TB_USERS AddUser(ESTM.Common.DtoModel.DTO_TB_USERS oUser) {
            return base.Channel.AddUser(oUser);
        }
        
        public System.Threading.Tasks.Task<ESTM.Common.DtoModel.DTO_TB_USERS> AddUserAsync(ESTM.Common.DtoModel.DTO_TB_USERS oUser) {
            return base.Channel.AddUserAsync(oUser);
        }
        
        public bool DeleteUser(ESTM.Common.DtoModel.DTO_TB_USERS oUser) {
            return base.Channel.DeleteUser(oUser);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteUserAsync(ESTM.Common.DtoModel.DTO_TB_USERS oUser) {
            return base.Channel.DeleteUserAsync(oUser);
        }
        
        public bool DeleteUserByLamada(Serialize.Linq.Nodes.ExpressionNode expressionNode) {
            return base.Channel.DeleteUserByLamada(expressionNode);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteUserByLamadaAsync(Serialize.Linq.Nodes.ExpressionNode expressionNode) {
            return base.Channel.DeleteUserByLamadaAsync(expressionNode);
        }
        
        public bool UpdateUser(ESTM.Common.DtoModel.DTO_TB_USERS oUser) {
            return base.Channel.UpdateUser(oUser);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateUserAsync(ESTM.Common.DtoModel.DTO_TB_USERS oUser) {
            return base.Channel.UpdateUserAsync(oUser);
        }
        
        public System.Collections.Generic.List<ESTM.Common.DtoModel.DTO_TB_DEPARTMENT> GetDepartments(Serialize.Linq.Nodes.ExpressionNode expressionNode) {
            return base.Channel.GetDepartments(expressionNode);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ESTM.Common.DtoModel.DTO_TB_DEPARTMENT>> GetDepartmentsAsync(Serialize.Linq.Nodes.ExpressionNode expressionNode) {
            return base.Channel.GetDepartmentsAsync(expressionNode);
        }
        
        public ESTM.Common.DtoModel.DTO_TB_DEPARTMENT AddDepartment(ESTM.Common.DtoModel.DTO_TB_DEPARTMENT oDept) {
            return base.Channel.AddDepartment(oDept);
        }
        
        public System.Threading.Tasks.Task<ESTM.Common.DtoModel.DTO_TB_DEPARTMENT> AddDepartmentAsync(ESTM.Common.DtoModel.DTO_TB_DEPARTMENT oDept) {
            return base.Channel.AddDepartmentAsync(oDept);
        }
        
        public bool DeleteDepartment(ESTM.Common.DtoModel.DTO_TB_DEPARTMENT oDept) {
            return base.Channel.DeleteDepartment(oDept);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteDepartmentAsync(ESTM.Common.DtoModel.DTO_TB_DEPARTMENT oDept) {
            return base.Channel.DeleteDepartmentAsync(oDept);
        }
        
        public bool DeleteDeptByLamada(Serialize.Linq.Nodes.ExpressionNode expressionNode) {
            return base.Channel.DeleteDeptByLamada(expressionNode);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteDeptByLamadaAsync(Serialize.Linq.Nodes.ExpressionNode expressionNode) {
            return base.Channel.DeleteDeptByLamadaAsync(expressionNode);
        }
        
        public bool UpdateDepartment(ESTM.Common.DtoModel.DTO_TB_DEPARTMENT oDept) {
            return base.Channel.UpdateDepartment(oDept);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateDepartmentAsync(ESTM.Common.DtoModel.DTO_TB_DEPARTMENT oDept) {
            return base.Channel.UpdateDepartmentAsync(oDept);
        }
        
        public System.Collections.Generic.List<ESTM.Common.DtoModel.DTO_TB_ROLE> GetRoles(Serialize.Linq.Nodes.ExpressionNode expressionNode) {
            return base.Channel.GetRoles(expressionNode);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ESTM.Common.DtoModel.DTO_TB_ROLE>> GetRolesAsync(Serialize.Linq.Nodes.ExpressionNode expressionNode) {
            return base.Channel.GetRolesAsync(expressionNode);
        }
        
        public ESTM.Common.DtoModel.DTO_TB_ROLE AddRole(ESTM.Common.DtoModel.DTO_TB_ROLE oRole) {
            return base.Channel.AddRole(oRole);
        }
        
        public System.Threading.Tasks.Task<ESTM.Common.DtoModel.DTO_TB_ROLE> AddRoleAsync(ESTM.Common.DtoModel.DTO_TB_ROLE oRole) {
            return base.Channel.AddRoleAsync(oRole);
        }
        
        public System.Collections.Generic.List<ESTM.Common.DtoModel.DTO_TB_MENU> GetMenus(Serialize.Linq.Nodes.ExpressionNode expressionNode) {
            return base.Channel.GetMenus(expressionNode);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ESTM.Common.DtoModel.DTO_TB_MENU>> GetMenusAsync(Serialize.Linq.Nodes.ExpressionNode expressionNode) {
            return base.Channel.GetMenusAsync(expressionNode);
        }
        
        public ESTM.Common.DtoModel.DTO_TB_MENU AddMenu(ESTM.Common.DtoModel.DTO_TB_MENU oMenu) {
            return base.Channel.AddMenu(oMenu);
        }
        
        public System.Threading.Tasks.Task<ESTM.Common.DtoModel.DTO_TB_MENU> AddMenuAsync(ESTM.Common.DtoModel.DTO_TB_MENU oMenu) {
            return base.Channel.AddMenuAsync(oMenu);
        }
    }
}
